project:
  title: "Intro to git"
  output-dir: "output"
  render:
    - "/*.qmd"
    - "resources/*/*.qmd"

author: "Jan Simson"
format:
  revealjs:
    incremental: true
revealjs-plugins:
  - attribution
title-slide-attributes:
    data-background-image: images/backgrounds/yancy-min-842ofHC6MaI-unsplash.jpg
    data-background-color: black
    data-background-opacity: "0.3"
