---
title: "Introduction to `git`"
author: "Jan Simson"
format:
  html:
    subtitle: "Course Materials for a One-Day Workshop"
    toc: true
    output-file: index.html
    theme: cosmo
    code-links:
      - text: Repository
        href: https://github.com/jansim/intro-to-git
        icon: github
        target: _blank
  gfm:
    toc: false
    output-file: README.md
format-links: false
---

This repository contains the course materials for a one-day workshop titled "Data Literacy: Introduction to `git`" which I gave at the Karlsruhe Institute for Technology (KIT).

<!--
  To update the README, render this file directly via
  quarto render README.qmd --to=gfm
-->

## Contents

### Slides

- Block 1: Introduction & Basics
  - 1.0 Intro [[slides]](https://simson.io/intro-to-git/1.0-intro.html)
  - 1.1 What is git? [[slides]](https://simson.io/intro-to-git/1.1-what_is_git.html)
  - 1.2 Tracking Changes [[slides]](https://simson.io/intro-to-git/1.2-tracking_changes.html)

- Block 2: Branches & More
  - 2.1 .gitignore [[slides]](https://simson.io/intro-to-git/2.1-gitignore.html)
  - 2.2 History [[slides]](https://simson.io/intro-to-git/2.2-history.html)
  - 2.3 Branches & Merging [[slides]](https://simson.io/intro-to-git/2.3-branches_merging.html)

- Block 3: Collaboration via Github
  - 3.1 What is GitHub? [[slides]](https://simson.io/intro-to-git/3.1-what_is_github.html)
  - 3.2 Synching Changes [[slides]](https://simson.io/intro-to-git/3.2-synching_changes.html)
  - 3.3 Markdown [[slides]](https://simson.io/intro-to-git/3.3-markdown.html)

- Block 4: Advanced Github & Beyond
  - 4.1 Advanced GitHub [[slides]](https://simson.io/intro-to-git/4.1-advanced_github.html)
  - 4.2 Final Notes [[slides]](https://simson.io/intro-to-git/4.2-final_notes.html)
  - *Outro*

- Bonus Practical [[slides]](https://simson.io/intro-to-git/6.0-bonus-practical.html)

<!-- *: Since they have to be manually generated, the PDF version of slides may be slightly outdated. Please refer to [this guide](https://revealjs.com/pdf-export/), on how to export your own PDF version from the online slides. -->

### Supporting Documents

- Supplementary [student information sheet](https://simson.io/intro-to-git/resources/student-info/student-info.pdf)
- How to Setup SSH authentication for GitHub [[PDF]](https://simson.io/intro-to-git/resources/ssh/how-to-setup-github-ssh.pdf) [[HTML]](https://lmu-osc.github.io/Introduction-RStudio-Git-GitHub/SSH.html)
  - By [Mike Croucher & Malika Ihle](https://github.com/lmu-osc/Introduction-RStudio-Git-GitHub)
- Git Cheatsheet [[PDF]](resources/git-cheat-sheet-education.pdf)
  - By [GitHub Education](https://education.github.com/)

## Links

- Repositories used in the Course
  - [Git Scavenger Hunt](https://github.com/open-teaching/git-scavenger-hunt)
  - [GitHub Pages Template](https://github.com/open-teaching/gh-pages-template)
  - [Collaborative Course Summary](https://github.com/open-teaching/git-course-summary-ws22)
    - Note: This repository may be turned private in the future.
- Guides to review & refresh your knowledge
  - <https://gitimmersion.com>
  - <https://github.com/git-guides>
  - [Introduction to RStudio Git & GitHub](https://lmu-osc.github.io/Introduction-RStudio-Git-GitHub/)
  - [The Carpentries: Version Control with Git](https://swcarpentry.github.io/git-novice/)
- Further reading (beyond the contents of the course)
  - [Trunk Based Development](https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development), a popular and advanced workflow of using git (currently concidered a best-practice)
  - Using git with data
    - [dvc](https://dvc.org/): Data Version Control
    - [git lfs](https://git-lfs.github.com/): Git Large File Storage
  - If you have a problem
    - [ohshitgit.com](https://ohshitgit.com/) [(🇩🇪)](https://ohshitgit.com/de)
    - Google: Just googling your problem is often the most useful solution
- Follow up course: <http://simson.io/advanced-git/>

## License

The contents of this course which were created by me are available under [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/). For resources where I do not own the copyright, other licenses may apply.
